Fix NoSuchMethodError when using Buildship 3.1.5
Support both Collection and Map values from `modelProvider.fetchModels`
so that the plugin can work with Builship 3.1.5.

Fixes gh-260